name: Docker Images CI

on:
  push:
    branches: [ master ]
    paths:
      - 'docker/Dockerfile*'
  pull_request:
    branches: [ master ]

jobs:

  build-deploy-cuda110:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the cuda 11.0 Docker image
      run: docker build . --file docker/Dockerfile --tag rexhaif/ml-toolbox:latest --tag rexhaif/ml-toolbox:cu110
    - name: Push cuda 11.0 to dockerhub
      run: echo ${password} | docker login -u ${username} --password-stdin && docker push rexhaif/ml-toolbox:latest && docker push rexhaif/ml-toolbox:cu110
      env:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
  build-deploy-cuda100:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the cuda 10.0 Docker image
      run: >
        docker build . --file docker/Dockerfile 
           --tag rexhaif/ml-toolbox:cu100 
           --build-arg BASE_IMAGE=nvidia/cuda:10.0-runtime-ubuntu18.04 
           --build-arg JAX_PACKAGE=https://storage.googleapis.com/jax-releases/cuda100/jaxlib-0.1.52-cp38-none-manylinux2010_x86_64.whl
           --build-arg PYTORCH_PACKAGE=torch==1.6.0+cu100
           --build-arg TF_PACKAGE=tensorflow
    - name: Push cuda 10.0 to dockerhub
      run: echo ${password} | docker login -u ${username} --password-stdin && docker push rexhaif/ml-toolbox:cu100
      env:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
  build-deploy-cuda101:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the cuda 10.1 Docker image
      run: >
        docker build . --file docker/Dockerfile 
           --tag rexhaif/ml-toolbox:cu101 
           --build-arg BASE_IMAGE=nvidia/cuda:10.1-runtime-ubuntu18.04 
           --build-arg JAX_PACKAGE=https://storage.googleapis.com/jax-releases/cuda101/jaxlib-0.1.52-cp38-none-manylinux2010_x86_64.whl
           --build-arg PYTORCH_PACKAGE=torch==1.6.0+cu101
           --build-arg TF_PACKAGE=tensorflow
    - name: Push cuda 10.1 to dockerhub
      run: echo ${password} | docker login -u ${username} --password-stdin && docker push rexhaif/ml-toolbox:cu101
      env:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
  build-deploy-cuda102:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the cuda 10.2 Docker image
      run: >
        docker build . --file docker/Dockerfile 
           --tag rexhaif/ml-toolbox:cu102
           --build-arg BASE_IMAGE=nvidia/cuda:10.2-runtime-ubuntu18.04 
           --build-arg JAX_PACKAGE=https://storage.googleapis.com/jax-releases/cuda102/jaxlib-0.1.52-cp38-none-manylinux2010_x86_64.whl
           --build-arg PYTORCH_PACKAGE=torch==1.6.0+cu102
           --build-arg TF_PACKAGE=tensorflow
    - name: Push cuda 10.2 to dockerhub
      run: echo ${password} | docker login -u ${username} --password-stdin && docker push rexhaif/ml-toolbox:cu102
      env:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
