name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the cuda 11.0 Docker image
      run: docker build . --file docker/Dockerfile.gpu --tag rexhaif/ml-toolbox:latest --tag rexhaif/ml-toolbox:cu110
    - name: Push cuda 11.0 to dockerhub
      run: echo ${password} | docker login -u ${username} --password-stdin && docker push rexhaif/ml-toolbox:latest && docker push rexhaif/ml-toolbox:cu110
      env:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
